# Generated by Django 3.2.6 on 2021-08-30 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abnormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abnor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eq_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Volt_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subeq_name', models.CharField(max_length=100)),
                ('eq_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadpic.equipment')),
                ('volt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadpic.voltage')),
            ],
        ),
        migrations.CreateModel(
            name='Job_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField(auto_now_add=True)),
                ('job_time', models.TimeField(auto_now_add=True)),
                ('job_picture', models.URLField(max_length=500)),
                ('abnor_other', models.CharField(blank=True, max_length=255, null=True)),
                ('abnor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadpic.abnormal')),
                ('job_officerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subeq_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadpic.sub_equipment')),
            ],
        ),
    ]
