# Generated by Django 3.2.6 on 2021-08-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_upload',
            name='abnor_name2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnor_name2', to='uploadpic.abnormal'),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='abnor_name3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnor_name3', to='uploadpic.abnormal'),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='abnor_other2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='abnor_other3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='subeq_name2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subeq_name2', to='uploadpic.sub_equipment'),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='subeq_name3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subeq_name3', to='uploadpic.sub_equipment'),
        ),
        migrations.AddField(
            model_name='sub_equipment',
            name='eq_name2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eq_name2', to='uploadpic.equipment'),
        ),
        migrations.AddField(
            model_name='sub_equipment',
            name='eq_name3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eq_name3', to='uploadpic.equipment'),
        ),
        migrations.AlterField(
            model_name='job_upload',
            name='abnor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnor_name', to='uploadpic.abnormal'),
        ),
        migrations.AlterField(
            model_name='job_upload',
            name='subeq_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subeq_name', to='uploadpic.sub_equipment'),
        ),
    ]
