# Generated by Django 3.2.6 on 2021-09-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpic', '0002_auto_20210831_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_upload',
            name='abnor_name2',
        ),
        migrations.RemoveField(
            model_name='job_upload',
            name='abnor_name3',
        ),
        migrations.RemoveField(
            model_name='job_upload',
            name='abnor_other2',
        ),
        migrations.RemoveField(
            model_name='job_upload',
            name='abnor_other3',
        ),
        migrations.RemoveField(
            model_name='job_upload',
            name='subeq_name2',
        ),
        migrations.RemoveField(
            model_name='job_upload',
            name='subeq_name3',
        ),
        migrations.RemoveField(
            model_name='sub_equipment',
            name='eq_name2',
        ),
        migrations.RemoveField(
            model_name='sub_equipment',
            name='eq_name3',
        ),
        migrations.RemoveField(
            model_name='job_upload',
            name='abnor_name',
        ),
        migrations.AddField(
            model_name='job_upload',
            name='abnor_name',
            field=models.ManyToManyField(to='uploadpic.Abnormal'),
        ),
        migrations.AlterField(
            model_name='job_upload',
            name='abnor_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_upload',
            name='subeq_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadpic.sub_equipment'),
        ),
    ]
