# Generated by Django 3.2.6 on 2021-09-08 05:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpic', '0004_auto_20210908_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_equipment',
            name='eq_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subeq_eq_list', to='uploadpic.equipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_equipment',
            name='volt_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subeq_volt_list', to='uploadpic.voltage'),
        ),
    ]
