# Generated by Django 3.2.6 on 2021-09-20 04:52

from django.db import migrations, models
import picwithmodel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageformodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagefromuser', models.ImageField(upload_to=picwithmodel.models.Uploadpath)),
                ('Equipmentfromuser', models.CharField(max_length=100)),
            ],
        ),
    ]
