# Generated by Django 3.2.6 on 2021-09-28 07:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picwithmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageformodel',
            name='Objects',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageformodel',
            name='Success',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageformodel',
            name='Time',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
