# Generated by Django 3.2.6 on 2021-09-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picwithmodel', '0003_alter_imageformodel_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageformodel',
            name='Objects',
        ),
        migrations.RemoveField(
            model_name='imageformodel',
            name='Success',
        ),
        migrations.RemoveField(
            model_name='imageformodel',
            name='Time',
        ),
    ]
