# Generated by Django 3.2.6 on 2021-09-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picwithmodel', '0005_auto_20210928_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageformodel',
            name='Equipmentfromuser',
        ),
    ]
