# Generated by Django 3.2.6 on 2021-09-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picwithmodel', '0006_remove_imageformodel_equipmentfromuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageformodel',
            name='Boxespic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
