# Generated by Django 3.2.6 on 2021-10-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picwithmodel', '0008_remove_imageformodel_boxespic'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageformodel',
            name='Lat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='imageformodel',
            name='Lng',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
