# Generated by Django 3.2.6 on 2021-10-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picwithmodel', '0009_auto_20211014_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageformodel',
            name='Lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imageformodel',
            name='Lng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
